# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDevAirBNB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDevAirBNB

pod 'Alamofire', '~> 4.0'
pod "Dip", '5.0.4'
pod "Dip-UI", '1.0.2'
pod 'GoogleMaps', '2.1.1'
pod "RappleProgressHUD" 

end
